zsisa flow + thermal work (#342)
* Modification on test_qha_general_stress.

* Made some modifications to qha_general_stress.py.

* Add ScrFile plot_freqs_at_ggp method

* Fix AttributeError: 'Arrow3D' object has no attribute 'do_3d_projection' raised by structure.plot()

* scr.reader --> scr.r, minor improvements in docs

* Don't deploy website on pull requests

* Cosmetic changes

* More Type hints, fix a couple of sphinx warnings

* update vars database

* Fix a couple of RST warnings

* app post-processing tools for QHA

* Saving work

* zsisa: add set_structure_stress_guess method + simplify if statements

* Use dataclasses instead of dictionaries

* Add Serializable mixin class

* More docs

* generate_deformations: return indices needed to insert PHDOSes in the 6d array

* Add .codespell.ignore

* Rename work.zsisa.cal_stress -> get_tstress and return ThermalData instance

* Activate elastic works

* model -> qha_model

* Use GPa_to_au from abinit_units

* if entry in phdos_6s is not None, path shall exist

* Finalize json format to support restart and post-processing

* Implement MultiRelaxTask

* Restore works.py to previous version

* Add register_multi_relax_task

* Finalize post-processing tools

* Use VzsisaResults

* Code cleanup

* Move prof_main to tools.cli_parsers

* Add support for tuna and snakeviz

* Add run_tests_on_changed.py

* Cosmetic changes

* Activate mypy

* Double relaxation only if optcell == 0

* Converge relaxation with thermal stress twice. Use dilatmx=1.0 in the second run

* Add with_piezo option. default: False

* Now structure_guess and stress_guess are removed from the __init__ and passed to get_tstress

* Fix Deprecation Warning: Conversion of an array with ndim > 0 to a scalar

* Plot only indipendent constants

* Renaming

* Gibbs free energy is added to ZSISA.

* Continue to fix deprecation warnings

* fix a problem.

* plot_elastic_vs_t_and_p

* Move cmat_inds_names to qha_general_stress

* Add plot_gibbs

* Add tests for gibbs and elastic tensor

* Cosmetic changes

* Clarify that get_tstress receives pressure in GPa

* Cosmetic changes

* fix pv in gibbs units.

* cosmetic changes

* Continue to fix deprecation warnings

* get_tstress now receives elastic tensort in Gpa and Voigt notation instead of filename

* Postpone import of Element

* Cosmetic changes

* Cosmetic changes

* Cosmetic changes

* Add some documentation

---------

Co-authored-by: Samare Rostami <samare.rostami@gmail.com>