cosmetic changes in RST files (#341)
* Add ScrFile plot_freqs_at_ggp method

* Fix AttributeError: 'Arrow3D' object has no attribute 'do_3d_projection' raised by structure.plot()

* scr.reader --> scr.r, minor improvements in docs

* Don't deploy website on pull requests

* Cosmetic changes

* More Type hints, fix a couple of sphinx warnings

* update vars database

* Fix a couple of RST warnings

* app post-processing tools for QHA